### ISSUE TITLE
I see the fps values but it doesn't recognize nobody

### ISSUE THREAD

**Issue by eren-erver** [pythonlessons/TensorFlow-2.3.1-YOLOv4-CSGO-aimbot#1]
First of all thank you for your videos and your contributions to the community. I just wanted to ask a question I tried to run Collect_training_data.py  It doesn't give any errors and it prints the fps values but it doesn't recognize the players.

**Comment by pythonlessons** [comment]
What os you have, have you tried to use cv2.imshow and to check what it sees?

**Comment by eren-erver** [comment]
its windows , ok I will try that

**Comment by eren-erver** [comment]
The problem is that with cv2.imshow it just shows me a black screen with no errors.

**Comment by pythonlessons** [comment]
This means you are grabbing something wrong, try to fix that first

**Comment by eren-erver** [comment]
I replaced
```
img = np.array(sct.grab({"top": 87-offset, "left": 1920, "width": 1280, "height": 720, "mon": -1}))
img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
```
with

```
monitor = {'top': 0, 'left': 0, 'width': 1920, 'height': 1080}
img = np.array(sct.grab(monitor))
img = np.flip(img[:, :, :3], 2)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
```
and it worked thanks

**Comment by pythonlessons** [comment]
why you do no.flip?

**Comment by eren-erver** [comment]
Idk really ,I was trying different things and this one worked :D

**Comment by eren-erver** [comment]
it probably worked because I changed cv2.COLOR_RGBA2RGB to cv2.COLOR_BGR2RGB
